name: Python Microservices with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write  # Allow pushing Docker images to GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Python environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        for service in product-service order-service inventory-service; do
          if [ -f $service/requirements.txt ]; then pip install -r $service/requirements.txt; fi
        done

    # Step 4: Lint with flake8
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Step 5: Debug test discovery
    - name: Debug test discovery
      run: |
        for service in product-service order-service inventory-service; do
          echo "Collecting tests for $service..."
          pytest $service/tests --collect-only
        done

    # Step 6: Run tests
    - name: Run tests
      run: |
        for service in product-service order-service inventory-service; do
          echo "Running tests for $service..."
          pytest $service/tests
        done

    # Step 7: Set IMAGE_TAG environment variable
    - name: Set IMAGE_TAG
      run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    # Step 8: Log in to GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.acto
